# This file was generated by GoReleaser. DO NOT EDIT.
class Assam < Formula
  desc "Get a credential by AssumeRoleWithSAML for AWS CLI and SDK"
  homepage ""
  version "1.2.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cybozu/assam/releases/download/v1.2.3/assam_1.2.3_Darwin_x86_64.tar.gz"
    sha256 "dc0abbbae38c07bb03ec90a435e6584111f82ed476968dad84fbc7d0898dc310"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cybozu/assam/releases/download/v1.2.3/assam_1.2.3_Linux_x86_64.tar.gz"
    sha256 "a4bb253db05a283c83b314bde8c2a2e3cb0d2b11b9393d46baeed9ce60a6ed55"
  end

  def install
    bin.install "assam"
  end
end
