# This file was generated by GoReleaser. DO NOT EDIT.
class Assam < Formula
  desc "Get a credential by AssumeRoleWithSAML for AWS CLI and SDK"
  homepage ""
  url "https://github.com/cybozu/assam/releases/download/v1.1.1/assam_1.1.1_Darwin_x86_64.tar.gz"
  version "1.1.1"
  sha256 "1ceef8362d03ba68d8e0b91fbbb441e7021afcdea6d55189e347767e9f08237c"

  def install
    bin.install "assam"
  end
end
